name: Package Java WAR into RPM with JBoss Web Server 5

on:
  release:
    types: [ created ]
    branches: [ releases/v7.2.* ]
  workflow_dispatch:
  pull_request:
    branches: [ releases/v7.2.* ]
  push:
    branches: [ releases/v7.2.* ]
env:
  HEALTH_WAIT_TIME: 200
  RPM_REPO_INIT_WAIT_TIME: 60
  RPM_REPO_NAME: 'openrouteservice-rpm'
  RPM_TESTING_REPO_NAME: 'openrouteservice-rpm-testing'
  RPM_REPO_TESTING_FOLDER: 'testing'
  RPM_REPO_SNAPSHOTS_FOLDER: 'snapshots'
  RPM_REPO_RELEASES_FOLDER: 'releases'
  DOCKER_BASE_IMAGE_TAG: '1'

jobs:
  prepare_docker_images:
    name: Build ${{ matrix.docker_file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_file: [ dockerfile-ubi8-java17-jws57 ]
        include:
          # If docker_file is dockerfile-ubi8-java17-jws57 set the following environment variables
          - docker_file: dockerfile-ubi8-java17-jws57
            DOCKER_HUB_IMAGE_NAME: heigit/ubi8-java17-jws57
            CONTAINER_NAME: ubi8-java17-jws57
            PUSH_TO_DOCKER_HUB: true
    steps:
      - name: Print Workflow Run ID
        run: |
          echo "Workflow Run ID: ${{ github.run_id }}"

      - name: Print the container logs for debugging
        shell: bash
        run: |
          ##### Print debugging info #####
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"

      - name: Get mvn project.version
        run: |
          echo "ORS_VERSION=1" >> "$GITHUB_ENV"


      - name: Print is VERSION contains SNAPSHOT
        shell: bash
        if: contains(env.ORS_VERSION, '1')
        run: |
          ##### Print debugging info #####
          echo "ORS_VERSION: ${{ env.ORS_VERSION }} "
          touch test.file

      - name: Attach RPM package to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: test.file
          asset_name: test.file
          asset_content_type: application/x-rpm

      - name: Upload the RPM package to the nexus releases rpm registry
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          echo "release upload ${{ env.ORS_VERSION }}"

          
      - name: Upload the snapshot RPM package to the nexus snapshots rpm registry
        # Only upload if this is a push on a release/v7.2.* branch
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/releases/v7.2.')
        run: |
          echo "snapshot upload ${{ env.ORS_VERSION }}"
